apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
  name: gpu-custom-metrics
  namespace: monitoring
spec:
  groups:
    - name: gpu-rule-group
      rules:
        - record: gpu_utilization_per_pod
          expr: DCGM_FI_DEV_GPU_UTIL{exported_pod!=""}
          labels:
            namespace: default
        - record: cuda_gpu
          expr: DCGM_FI_DEV_GPU_UTIL{exported_pod=~"gpu-workload.*"}
          labels:
            namespace: default
            deployment: gpu-workload
        - record: pod_gpu_utilization
          expr: label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL, "pod", "$1", "exported_pod", "(.*)"), "namespace", "$1", "exported_namespace", "(.*)")
