kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: ai-conformance
  namespace: garden-core
spec:
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-central-1a
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker-cpu
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: m5.large
          image:
            name: gardenlinux
            version: 1877.5.0
          architecture: amd64
        zones:
          - eu-central-1a
        cri:
          name: containerd
        volume:
          type: gp3
          size: 50Gi
      - name: worker-gpu
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: g4dn.xlarge
          image:
            name: gardenlinux
            version: 1877.5.0
          architecture: amd64
        zones:
          - eu-central-1a
        cri:
          name: containerd
        volume:
          type: gp3
          size: 50Gi
  networking:
    nodes: 10.180.0.0/16
    type: calico
  kubernetes:
    version: 1.33.4
    kubeAPIServer:
      featureGates:
        DynamicResourceAllocation: true
      runtimeConfig:
        resource.k8s.io/v1beta1: true
    kubeControllerManager:
      featureGates:
        DynamicResourceAllocation: true
      horizontalPodAutoscaler:
        syncPeriod: 5s
        tolerance: 0.1
        downscaleStabilization: 10s
        initialReadinessDelay: 10s
        cpuInitializationPeriod: 10s
    kubeScheduler:
      featureGates:
        DynamicResourceAllocation: true
    kubelet:
      featureGates:
        DynamicResourceAllocation: true
    clusterAutoscaler:
      maxGracefulTerminationSeconds: 0
      newPodScaleUpDelay: 0s
      scaleDownDelayAfterAdd: 300s
      scaleDownDelayAfterDelete: 0s
      scaleDownDelayAfterFailure: 1m
      scaleDownUnneededTime: 10s
      scaleDownUtilizationThreshold: 0.5
      scanInterval: 5s
  cloudProfile:
    name: aws
    kind: CloudProfile
  purpose: evaluation
  region: eu-central-1
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 220000+0200
      end: 230000+0200
  credentialsBindingName: shoot-operator-aws-team
  hibernation:
    schedules:
      - location: Europe/Berlin
        start: 00 18 * * 1,2,3,4,5,6,0
